packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
allowBuilds:
  '@firebase/util': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - google-auth-library@11.0.0
