import { ThemeColors } from '../theme/tokens';

export const getStyles = (colors: ThemeColors, isDarkMode: boolean) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 24,
    justifyContent: 'center' as const,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center' as const,
    maxWidth: 400,
    width: '100%' as const,
    alignSelf: 'center' as const,
  },
  backButton: {
    position: 'absolute' as const,
    top: 50,
    left: 24,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    borderWidth: isDarkMode ? 0 : 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
  },
  iconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: isDarkMode ? '#452a0a' : '#fdf3c7',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textMuted,
    marginBottom: 40,
  },
  label: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.textMuted,
    marginBottom: 8,
    letterSpacing: 1,
  },
  phoneInputContainer: {
    flexDirection: 'row' as const,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
    height: 56,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  phonePrefix: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
    marginRight: 12,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
  },
  standardInputContainer: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
    height: 56,
    justifyContent: 'center' as const,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  dropdownContainer: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
    height: 56,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  button: {
    height: 56,
    borderRadius: 12,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.primary,
    marginTop: 16,
  },
  buttonDisabled: {
    backgroundColor: isDarkMode ? '#262626' : '#e5e7eb',
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold' as const,
    color: '#ffffff',
  },
  buttonTextDisabled: {
    color: '#9ca3af',
  },
  termsText: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center' as const,
    marginTop: 40,
  },
  linkText: {
    color: colors.primary,
    fontWeight: '600' as const,
    textDecorationLine: 'underline' as const,
  },
  separatorContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginVertical: 24,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  separatorText: {
    marginHorizontal: 16,
    color: colors.textMuted,
    fontSize: 14,
  },
  googleButton: {
    height: 56,
    borderRadius: 12,
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: 'bold' as const,
    color: colors.text,
    marginLeft: 12,
  },
  bottomTextContainer: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    marginTop: 24,
  },
  bottomText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  otpContainer: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 40,
  },
  otpInput: {
    width: 48,
    height: 56,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: isDarkMode ? 'transparent' : colors.border,
    fontSize: 24,
    textAlign: 'center' as const,
    fontWeight: '600' as const,
    color: colors.text,
  },
  otpInputActive: {
    borderColor: colors.primary,
    backgroundColor: isDarkMode ? '#171717' : '#ffffff',
  },
  resendText: {
    textAlign: 'center' as const,
    color: colors.textMuted,
    fontSize: 14,
  },
});
